### ISSUE TITLE
tlm-launcher child processes not terminated with tlm

### ISSUE THREAD

**Issue by jlaako** [01org/tlm#64]
Platform: Debian Stretch (at least)

When tlm is stopped using "systemctl stop tlm", tlm-launcher is also terminated, but child processes started by tlm-launcher are left running.

For example if session script is:
#!/bin/sh
#
export DBUS_SESSION_BUS_DIR=$XDG_RUNTIME_DIR/dbus
export DBUS_SESSION_BUS_ADDRESS=unix:path=$DBUS_SESSION_BUS_DIR/user_bus_socket
exec tlm-launcher -f /etc/session.d/user-session-launch-script

And user-session-launch-script:
M:/etc/session.d/dbus-session
L:/usr/bin/rygel

And dbus-session script is:
#!/bin/sh
#
mkdir -p $DBUS_SESSION_BUS_DIR
exec /usr/bin/dbus-daemon --session --address=$DBUS_SESSION_BUS_ADDRESS --nopidfile --nofork

**Comment by avalluri** [comment]
Yes, its quite possible ;-) as the monitoring process is a shell script, we can only monitor the shell process, but not the execs inside the script i guess :(

**Comment by jlaako** [comment]
Fixed in https://github.com/01org/tlm/pull/65

**Comment by jlaako** [comment]
@avalluri bash man page says following:
 exec [-cl] [-a name] [command [arguments]]
              If command is specified, it replaces the shell.  No new  process
              is  created.  The arguments become the arguments to command.
