### ISSUE TITLE
Fix signal handler

### ISSUE THREAD

**Issue by elfring** [01org/tlm#66]
[The function "DBG"](https://developer.gnome.org/glib/stable/glib-Message-Logging.html#g-debug "Log a debug message.") does not belong to the list of [async-signal-safe functions](https://www.securecoding.cert.org/confluence/display/c/SIG30-C.+Call+only+asynchronous-safe+functions+within+signal+handlers "Call only asynchronous-safe functions within signal handlers.").
How do you think about to delete its call from your function "[_on_signal_cb](https://github.com/01org/tlm/blob/f5c760ed5a4cc89924f98b632351f3ec2a6cd660/src/plugins/default/tlm-auth-plugin-default.c#L99 "Check signal handling implementation.")"?

**Comment by jlaako** [comment]
I think both DBG and WARN should be removed, it could instead emit failure signal from there in case of failure.

**Comment by jlaako** [comment]
This item is now fixed as part of PR https://github.com/01org/tlm/pull/68
